language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm test
  - npm run build
  - npm run beforeDeploy
deploy:
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: build
  on:
    branch: development
  provider: pages
  skip-cleanup: true
  target-branch: master
